# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=25, unique=True, verbose_name='ID textual')),
                ('headline', models.CharField(max_length=200, verbose_name='título')),
                ('html_text', models.TextField(verbose_name='conteúdo HTML')),
            ],
            options={
                'verbose_name': 'conteúdo',
                'verbose_name_plural': 'conteúdos',
            },
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=50, verbose_name='texto alternativo (ALT)')),
                ('image', models.ImageField(upload_to='core/static/images/content/', verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='nome completo')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='email')),
                ('linkedin', models.CharField(blank=True, max_length=50, verbose_name='LinkedIn ID')),
                ('github', models.CharField(blank=True, max_length=50, verbose_name='GitHub ID')),
                ('program', models.CharField(blank=True, choices=[('BCC', 'Bacharelado em Ciência da Computação'), ('EnC', 'Engenharia de Computação')], max_length=3, verbose_name='curso')),
                ('type', models.CharField(choices=[('COOR', 'Docente Coordenador'), ('GRAD', 'Estudante de Graduação'), ('EXTR', 'Participante Externo')], max_length=4, verbose_name='tipo')),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo'), ('AF', 'Afastado')], max_length=2, verbose_name='status')),
                ('dateIn', models.DateField(verbose_name='data de início')),
                ('dateOut', models.DateField(blank=True, null=True, verbose_name='data de saída')),
                ('image', models.ImageField(blank=True, upload_to='core/static/images/members/', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'membro',
                'verbose_name_plural': 'membros',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='nome')),
                ('price', models.FloatField(verbose_name='valor')),
            ],
            options={
                'verbose_name': 'plano de apoio',
                'verbose_name_plural': 'planos de apoio',
            },
        ),
        migrations.CreateModel(
            name='PlanBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(unique=True, verbose_name='prioridade')),
                ('benefit', models.CharField(max_length=500, verbose_name='benefício')),
            ],
            options={
                'verbose_name': 'benefício de plano de apoio',
                'verbose_name_plural': 'benefícios de plano de apoio',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'tipo de plano de apoio',
                'verbose_name_plural': 'tipos de plano de apoio',
            },
        ),
        migrations.CreateModel(
            name='Supporters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='organização')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('fone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('page', models.CharField(blank=True, max_length=100, verbose_name='site')),
                ('value', models.FloatField(verbose_name='valor')),
                ('start_date', models.DateField(null=True, verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de fim')),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo'), ('SP', 'Sem Pagamento')], max_length=2, verbose_name='Status')),
                ('pay_date', models.DateField(null=True, verbose_name='data de pagamento')),
                ('image', models.ImageField(upload_to='core/static/images/supporters/', verbose_name='logo')),
                ('notes', models.TextField(blank=True, verbose_name='anotações')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Plan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'Apoiador',
                'verbose_name_plural': 'Apoiadores',
            },
        ),
        migrations.AddField(
            model_name='planbenefit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlanType', verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='plan',
            name='benefits',
            field=models.ManyToManyField(to='core.PlanBenefit', verbose_name='benefícios'),
        ),
        migrations.AddField(
            model_name='plan',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlanType', verbose_name='tipo'),
        ),
    ]
