# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionProcess',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='processo ID')),
                ('status', models.CharField(choices=[('EB', 'Em Breve'), ('EA', 'Em Andamento'), ('EN', 'Encerrado')], max_length=2, verbose_name='status')),
                ('application', models.URLField(max_length=100, verbose_name='link formulário')),
                ('announcement', models.FileField(upload_to='core/static/files/editais/', verbose_name='edital')),
            ],
            options={
                'verbose_name': 'processo seletivo',
                'verbose_name_plural': 'processos seletivos',
            },
        ),
        migrations.CreateModel(
            name='SelectionProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=100, verbose_name='título da etapa')),
                ('date', models.CharField(max_length=100, verbose_name='datas e horários')),
                ('status', models.CharField(choices=[('EB', 'Em Breve'), ('EA', 'Em Andamento'), ('EN', 'Encerrada')], max_length=2, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='resultados')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SelectionProcess', verbose_name='processo')),
            ],
            options={
                'verbose_name': 'processo seletivo - etapa',
                'verbose_name_plural': 'processo seletivo - etapas',
            },
        ),
        migrations.AlterField(
            model_name='supporters',
            name='status',
            field=models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo'), ('SP', 'Sem Pagamento')], max_length=2, verbose_name='status'),
        ),
    ]
