# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170821_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['full_name'], 'verbose_name': 'membro', 'verbose_name_plural': 'membros'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['type'], 'verbose_name': 'plano de apoio', 'verbose_name_plural': 'planos de apoio'},
        ),
        migrations.AlterModelOptions(
            name='plantype',
            options={'ordering': ['type'], 'verbose_name': 'plano de apoio - tipo', 'verbose_name_plural': 'plano de apoio - tipos'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['title'], 'verbose_name': 'trilha', 'verbose_name_plural': 'trilhas'},
        ),
        migrations.AlterModelOptions(
            name='supporters',
            options={'ordering': ['name'], 'verbose_name': 'Apoiador', 'verbose_name_plural': 'Apoiadores'},
        ),
        migrations.AlterModelOptions(
            name='workshopdates',
            options={'ordering': ['workshop'], 'verbose_name': 'workshop data', 'verbose_name_plural': 'workshop datas'},
        ),
        migrations.AlterModelOptions(
            name='workshopguests',
            options={'ordering': ['workshop'], 'verbose_name': 'workshop convidados', 'verbose_name_plural': 'workshop convidados'},
        ),
    ]
