# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_selectionprocess_notes'),
        ('core', '0007_auto_20170821_0148'),
    ]

    operations = [
    ]
