# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20170824_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshopguests',
            options={'ordering': ['name'], 'verbose_name': 'workshop convidados', 'verbose_name_plural': 'workshop convidados'},
        ),
        migrations.RemoveField(
            model_name='workshopguests',
            name='workshop',
        ),
        migrations.AddField(
            model_name='workshop',
            name='application',
            field=models.URLField(default='http://www.google.com', max_length=100, verbose_name='link formulário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='guests',
            field=models.ManyToManyField(blank=True, to='core.WorkshopGuests', verbose_name='convidados'),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='status',
            field=models.CharField(choices=[('EB', 'Em Breve'), ('EA', 'Em Andamento'), ('FI', 'Finalizado')], max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='supporters',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='supporters',
            name='page',
            field=models.URLField(blank=True, max_length=100, verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('EB', 'Em Breve'), ('EA', 'Em Andamento'), ('FI', 'Finalizado')], max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='workshopguests',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='workshopguests',
            name='page',
            field=models.URLField(blank=True, max_length=100, verbose_name='web page'),
        ),
    ]
