# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170824_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopdates',
            name='workshop',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='guests',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(verbose_name='detalhes HTML'),
        ),
        migrations.DeleteModel(
            name='WorkshopDates',
        ),
        migrations.DeleteModel(
            name='WorkshopGuests',
        ),
    ]
