# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170824_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopGroupClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100, verbose_name='turma')),
                ('date', models.CharField(max_length=100, verbose_name='dia e data')),
                ('time', models.CharField(max_length=100, verbose_name='horários')),
                ('location', models.CharField(max_length=100, verbose_name='local')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='notas rápidas')),
                ('application', models.URLField(max_length=100, verbose_name='link formulário')),
            ],
            options={
                'verbose_name': 'turma de workshop',
                'verbose_name_plural': 'turmas de workshops',
                'ordering': ['group'],
            },
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='workshops',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='application',
        ),
        migrations.AddField(
            model_name='workshop',
            name='dates_notes',
            field=models.CharField(blank=True, max_length=100, verbose_name='notas sobre datas e turmas'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='helpers',
            field=models.ManyToManyField(blank=True, null=True, related_name='workshop_workshop_helpers', to='core.Members', verbose_name='auxiliares'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='instructors',
            field=models.ManyToManyField(related_name='workshop_workshop_instructors', to='core.Members', verbose_name='instrutores'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Specialization', verbose_name='trilha?'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='workshopgroupclass',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Workshop', verbose_name='workshop'),
        ),
    ]
