# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170825_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopgroupclass',
            name='group',
            field=models.CharField(blank=True, max_length=100, verbose_name='turma'),
        ),
    ]
