# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170825_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopgroupclass',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workshopgroupclass',
            name='location',
        ),
        migrations.RemoveField(
            model_name='workshopgroupclass',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='workshopgroupclass',
            name='time',
        ),
        migrations.AddField(
            model_name='workshopgroupclass',
            name='details',
            field=models.TextField(default='', verbose_name='dia, hora, local'),
            preserve_default=False,
        ),
    ]
