# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170825_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporters',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='supporters',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='supporters',
            name='start_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='pgcode',
            field=models.CharField(blank=True, max_length=50, verbose_name='código plano PagSeguro'),
        ),
    ]
