# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170828_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price'], 'verbose_name': 'plano de apoio', 'verbose_name_plural': 'planos de apoio'},
        ),
    ]
