# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170828_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['type'], 'verbose_name': 'plano de apoio', 'verbose_name_plural': 'planos de apoio'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='pgcode',
            field=models.URLField(blank=True, max_length=50, verbose_name='URL PagSeguro'),
        ),
    ]
