# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170828_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('IA', 'Inscrições Abertas'), ('VP', 'Vagas Preenchidas'), ('EB', 'Em Breve'), ('EA', 'Em Andamento'), ('EN', 'Encerrado')], max_length=2, verbose_name='status'),
        ),
    ]
