# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170924_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='helpers',
            field=models.ManyToManyField(blank=True, related_name='workshop_workshop_helpers', to='core.Members', verbose_name='auxiliares'),
        ),
    ]
