# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20170924_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='pgcode',
        ),
    ]
